-- Inserting data into the categories table

INSERT INTO categories (category_id, name, description)
VALUES
  (1, 'Mobiles', 'Buy and sell mobile phones, sim cards, mobile accessories and mobile phone services near you.'),
  (2, 'Electronics', 'One of our most popular marketplace categories, where you can buy and sell almost any electrical item you can think of. There are mobile phones for sale, desktop computers, laptops, tablets, TVs, cameras, video games and much more.'),
  (3, 'Home & Living', 'A range of new and used home appliances listed by private sellers and businesses. Many bargains available for furniture, microwave ovens, kitchenware, office furniture, antiques and much more. It''s not just about the home either, you will find items for the garden such as tools, materials and gardening products.'),
  (4, 'Men''s Fashion & Grooming', 'gorgeous amongst simple'),
  (5, 'Women''s Fashion & Beauty', 'so elegant, so beautiful, just looking like a wow'),
  (6, 'Pets & Animals', 'Search through a wide variety of pets, farm animals and livestock for sale, or if you are selling your animals you can list it here and sell it quickly and easily.'),
  (7, 'Hobbies, Sports & Kids', 'Here is the place to pick up a great bargain when you are searching for musical instruments, sports equipment, movies, tickets, art and don''t forget the kids, we have lots of children''s items too!'),
  (8, 'Business & Industry', 'Looking to trade or do business in Bangladesh, this lively marketplace is where businesses offer their services to other businesses and customers.'),
  (9, 'Education', 'A range of educational items and services, both offered and wanted, including books, tuition and classes.'),
  (10, 'Essentials', 'Find daily essential products, including groceries, healthcare products, household items, fruits & vegetables, meat & seafood and baby products near you.'),
  (11, 'Agriculture', 'Find agricultural products, including fresh crop seeds, plants and fertilizers in Bangladesh.'),
  (12, 'Vehicles', 'Explore a wide range of vehicles including cars, motorcycles, boats, and trucks for buying and selling.'),
  (13, 'Real Estate', 'Find or list properties for sale and rent, including apartments, houses, land, and commercial spaces.'),
  (14, 'Services', 'Discover services ranging from educational tutoring, cleaning, repairs, to personal training and legal advice.'),
  (15, 'Jobs', 'Browse job listings across various industries or post vacancies to find the ideal candidate.'),
  (16, 'Travel & Leisure', 'Find travel deals, equipment, and leisure activities like camping gear, fitness equipment, and books.'),
  (17, 'Books, Movies & Music', 'Buy and sell books, DVDs, CDs, and instruments; a haven for entertainment and learning materials.'),
  (18, 'Art & Collectibles', 'Dive into the world of art and collectibles where you can find paintings, sculptures, rare items, and vintage collections.'),
  (19, 'Health & Beauty', 'Access a range of products and services for health and beauty including cosmetics, skincare, nutritional supplements, and medical equipment.'),
  (20, 'Tools & DIY', 'Find everything you need for your DIY projects, including tools, construction materials, and gardening equipment.'),
  (21, 'Event Management', 'Everything you need for managing events from planning services, decorations, to catering and photography services.'),
  (22, 'Furniture & Home Decor', 'Discover a wide range of furniture and home decor items to beautify your living spaces.'),
  (23, 'Kitchen & Dining', 'Find kitchen gadgets, dining sets, and all essentials for your cooking and dining needs.'),
  (24, 'Bath & Bedding', 'Explore our selection of bedding, towels, and bathroom accessories for comfort and decor.'),
  (25, 'Garden & Outdoor', 'Shop for garden tools, outdoor furniture, and everything you need to enjoy your outdoor space.'),
  (26, 'Computers & Accessories', 'Your one-stop-shop for computers, peripherals, and all types of accessories.'),
  (27, 'Mobile Accessories', 'Find cases, chargers, headphones, and all sorts of accessories for your mobile devices.'),
  (28, 'Photography & Videography', 'For professionals and hobbyists alike, find cameras, lenses, and equipment for your photography and videography projects.'),
  (29, 'Sports & Fitness', 'Gear up with our range of sports equipment, workout gear, and fitness accessories.'),
  (30, 'Musical Instruments', 'Discover musical instruments, from guitars to pianos, and equipment for musicians of all levels.'),
  (31, 'Board Games & Puzzles', 'Engage with a variety of board games, puzzles, and mind-challenging activities for all ages.'),
  (32, 'Toys & Games', 'Browse through a wide selection of toys and games for children of all ages.'),
  (33, 'Crafts & Sewing', 'Find supplies for your crafting and sewing projects, from fabrics to sewing machines.'),
  (34, 'Pet Supplies', 'Shop for your furry, feathered, or scaly friends with our range of pet foods, toys, and accessories.'),
  (35, 'Office Supplies', 'Equip your workspace with our selection of office supplies, from pens and paper to office furniture.'),
  (36, 'Beauty & Personal Care', 'Explore beauty products and personal care items for your daily regimen.'),
  (37, 'Groceries & Food', 'Get your daily essentials, fresh produce, and gourmet items from our groceries section.'),
  (38, 'Beverages', 'Discover a variety of drinks, from coffee and tea to soft drinks and alcoholic beverages.'),
  (39, 'Snacks & Confectionery', 'Treat yourself with our assortment of snacks, chocolates, and sweets.'),
  (40, 'Healthcare Products', 'Find healthcare and wellness products, including over-the-counter medicines, supplements, and personal health items.'),
  (41, 'Baby Products', 'Shop for baby essentials, from feeding and nursing items to diapers and baby gear.');