INSERT INTO items (user_id, category_id, subcategory_id, name, description, image, price, status) VALUES
  (1, 1, 1, 'Samsung Galaxy S21', 'Latest model with 5G connectivity.', 'url_to_samsung_galaxy_s21_image.jpg', 999, 'Available'),
  (2, 2, 7, 'Dyson V11 Vacuum Cleaner', 'Powerful suction, cord-free vacuum.', 'url_to_dyson_v11_image.jpg', 599, 'Sold'),
  (3, 3, 3, 'Oak Wood Dining Table', 'Elegant dining table made from oak wood.', 'url_to_dining_table_image.jpg', 450, 'Available'),
  (4, 4, 2, 'Levi''s Denim Jacket', 'Stylish denim jacket for men.', 'url_to_denim_jacket_image.jpg', 120, 'Available'),
  (5, 5, 1, 'Maxi Dress Floral Print', 'Beautiful floral print maxi dress for women.', 'url_to_maxi_dress_image.jpg', 89, 'Pending'),
  (6, 6, 1, 'Golden Retriever Puppy', 'Adorable golden retriever puppy, 8 weeks old.', 'url_to_puppy_image.jpg', 300, 'Available'),
  (7, 7, 2, 'Adidas Running Shoes', 'High-performance running shoes for athletes.', 'url_to_running_shoes_image.jpg', 110, 'Available'),
  (8, 8, 1, 'Office Desk Chairs', 'Ergonomic office chairs for productivity.', 'url_to_office_chair_image.jpg', 200, 'Sold'),
  (9, 9, 1, 'Physics Textbook', 'Comprehensive physics textbook for undergraduates.', 'url_to_physics_textbook_image.jpg', 60, 'Available'),
  (10, 10, 2, 'Organic Vegetables Box', 'A box of fresh, organic vegetables.', 'url_to_vegetables_box_image.jpg', 30, 'Available'),
  (11, 11, 1, 'High-Quality Seeds', 'Seeds for various vegetables and fruits.', 'url_to_seeds_image.jpg', 15, 'Available'),
  (12, 1, 1, 'iPhone 12', 'A14 Bionic chip, 5G speed.', 'image_iphone12.jpg', 799, 'Available'),
  (13, 2, 8, 'Canon EOS R5', 'High-resolution mirrorless camera.', 'image_canonEOSR5.jpg', 3899, 'Available'),
  (14, 3, 3, 'Solid Wood Bed Frame', 'Queen size bed frame made from solid wood.', 'image_bedFrame.jpg', 450, 'Sold'),
  (15, 4, 10, 'Seiko Automatic Watch', 'Stainless steel watch with see-through back.', 'image_seikoWatch.jpg', 525, 'Available'),
  (16, 5, 7, 'Skin Care Set', 'Complete skincare routine package.', 'image_skincareSet.jpg', 120, 'Available'),
  (17, 6, 1, 'Aquarium Set', '20-gallon fish tank with filter and lights.', 'image_aquarium.jpg', 150, 'Available'),
  (18, 7, 2, 'Golf Clubs Set', 'Full set of irons and woods, bag included.', 'image_golfClubs.jpg', 780, 'Pending'),
  (19, 8, 4, '3D Printer', 'High precision 3D printer for professional use.', 'image_3dPrinter.jpg', 1200, 'Available'),
  (20, 9, 1, 'Calculus Textbook', 'Comprehensive guide to calculus.', 'image_calculusBook.jpg', 95, 'Available'),
  (21, 10, 3, 'Fresh Salmon Fillet', 'Wild-caught salmon, 2 lbs.', 'image_salmonFillet.jpg', 22, 'Available'),
  (22, 11, 2, 'Gardening Tool Set', 'Essential tools for gardening enthusiasts.', 'image_gardeningTools.jpg', 75, 'Sold'),
  (23, 2, 11, 'Gaming Console', 'Latest gaming console with two controllers.', 'image_gamingConsole.jpg', 500, 'Available'),
  (24, 3, 5, 'Modern Lamp', 'LED lamp with adjustable brightness.', 'image_modernLamp.jpg', 89, 'Available'),
  (25, 4, 1, 'Running Shoes', 'Lightweight running shoes for men.', 'image_runningShoes.jpg', 110, 'Available'),
  (26, 5, 5, 'Heels', 'Elegant high heels in black.', 'image_heels.jpg', 130, 'Available'),
  (27, 6, 3, 'Cat Tree', 'Multi-level cat tree with scratching posts.', 'image_catTree.jpg', 60, 'Pending');
